### ISSUE TITLE
Bug in finalization

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-ioz#7]
Reported by @alexandru. This may be the same bug identified by @wi101. 

> Ah, you're right, so you are sequencing the execution of finalisers. Except that I found a bug, some sort of race condition.

Sample 1 — in which the inner finalizer never gets executed:
```
    val task = IO.unit[Void].bracket[Unit] { _ =>
      IO.sync[Void, Unit](println("start 1")) *> IO.sleep(1.second) *> IO.sync(println("release 1"))
    } { _ =>
      IO.unit[Void].bracket[Unit] { _ =>
        IO.sync[Void, Unit](println("start 2")) *> IO.sleep(1.second) *> IO.sync(println("release 2"))
      } { _ =>
        IO.never[Void, Unit]
      }
    }
    task.fork.flatMap(f => f.interrupt(new RuntimeException("cancel")) *> IO.never)
```
> This fails with:
```
java.lang.Error: Defect: Fiber is not in executing or async state
	at scalaz.ioeffect.RTS$FiberContext.enterAsyncStart(RTS.scala:931)
	at scalaz.ioeffect.RTS$FiberContext.evaluate(RTS.scala:514)
	at scalaz.ioeffect.RTS$FiberContext.$anonfun$fork$1(RTS.scala:761)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scalaz.ioeffect.RTS$$anon$1.run(RTS.scala:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
start 1
release 1
```
> Sample 2 — the first specified finalizer gets executed twice somehow, which is really odd:
```
    IO.unit[Void]
      .bracket[Unit](_ => IO.sync[Void, Unit](println("start 1")) *> IO.sleep(1.second) *> IO.sync(println("release 1")))(_ => IO.unit[Void])
      .bracket[ExitStatus](_ => IO.sync[Void, Unit](println("start 2")) *> IO.sleep(1.second) *> IO.sync(println("release 2")))(_ => IO.sync(ExitStatus.ExitNow(0)))
      .fork.flatMap(f => f.interrupt(new RuntimeException("cancel")) *> IO.never)
Output:

start 1
start 1
java.lang.Error: Defect: Fiber is not in executing or async state
	at scalaz.ioeffect.RTS$FiberContext.enterAsyncStart(RTS.scala:931)
	at scalaz.ioeffect.RTS$FiberContext.evaluate(RTS.scala:514)
	at scalaz.ioeffect.RTS$FiberContext.$anonfun$fork$1(RTS.scala:761)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scalaz.ioeffect.RTS$$anon$1.run(RTS.scala:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
release 1
```
> And this behavior is what made me jump to conclusions.

**Comment by alexandru** [comment]
Note that in the first sample the second finalizer doesn't necessarily needs to run because the `use` is probably not evaluated yet, what's worrying there is just the exception.

The second sample should be more worrying, as the installed finalizer gets started twice and that's usually the symptom of an ugly race condition (a multi-threading issue?). It's reproducible though, so should be easy to discover.

Some details:

- I used `SafeApp`
- tested with `"org.scalaz" %% "scalaz-ioeffect" % "2.3.0"`

**Comment by jdegoes** [comment]
Based on a preliminary analysis of this code, there are three valid outputs for this fragment.

**If interrupted before the action starts***

```
```

**Explanation**: The action is interrupted before it starts, so it prints out nothing.

**If interrupted inside the outer bracket but before the inner one***

```
start 1
release 1
```

**Explanation**: The action is interrupted after the outer resource is acquired, but before the inner resource is acquired, so when it is interrupted, the outer finalizer will be run and print out the messages.

**If interrupted inside both the outer and inner bracket***

```
start 2
release 2
start 1
release 1
```

**Explanation**: The action is interrupted after the outer and inner resources is acquired, so when it is interrupted, the inner finalizer will be run and print out the messages first, and then the outer finalizer will be run and print out the messages second.

**Comment by jdegoes** [comment]
*Simplified*

```scala
val bracket1 = 
  IO.unit.ensuring(putStrLn("start 1") *> IO.sleep(1.second) *> putStrLn("release 1"))

val bracket2 = bracket1.bracket(_ => 
  putStrLn("start 2") *> IO.sleep(1.second) *> putStrLn("release 2")) { 
  _ => IO.sync(ExitStatus.ExitNow(0))
}

bracket2.fork.flatMap(_.interrupt(new RuntimeException("cancel")) *> IO.never)
```

**If interrupted before anything is run**

```

```

**If interrupted at any other time**

```
start 1
release 1

start 2
release 2
```

**Comment by jdegoes** [comment]
```scala
buffer <- IORef[List[String]](Nil)
...
def print(text: String): IO[Void, Unit] = buffer.modify(l => text :: l)
...
print("release 1")
```
